apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: exercises
  name: app-storage-claim
spec:
  storageClassName: app-storage-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi