apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  namespace: exercises
  name: ping-pong-server
spec:
  replicas: 4
  strategy:
    canary:
      steps:
      - setWeight: 50
      - analysis:
          templates:
          - templateName: cpu-rate
  selector:
    matchLabels:
      app: ping-pong-server
  template:
    metadata:
      labels:
        app: ping-pong-server
    spec:
      containers:
        - name: app
          image: kuzn2k/ping-pong-server:1.0.9
          imagePullPolicy: Always
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
               path: /healthz
               port: 3000          
          env:
            - name: PORT
              value: "3000"
            - name: PGHOST
              value: "postgress-svc"
            - name: PGPORT
              value: "5432"
            - name: PGUSER
              value: "postgres"
            - name: PGPASSWORD
              value: ""
            - name: PGDATABASE
              value: "postgres"
          ports:
            - name: ping-port
              containerPort: 3000
